// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnWIdBQ4DbNQKtKwmaXYihs-dGvupLT10',
    appId: '1:147028699252:web:7d0f175106e49ac17c8921',
    messagingSenderId: '147028699252',
    projectId: 'thriller-multiverse',
    authDomain: 'thriller-multiverse.firebaseapp.com',
    storageBucket: 'thriller-multiverse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPNAzFzgi1_6IUwdfmU4xBGtajzO2ZbM',
    appId: '1:147028699252:android:c27551fcebc1d71c7c8921',
    messagingSenderId: '147028699252',
    projectId: 'thriller-multiverse',
    storageBucket: 'thriller-multiverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLh4xpgMFfV5v1x6nlfaR0j66o7uu5yE',
    appId: '1:147028699252:ios:11a51af79fe2028d7c8921',
    messagingSenderId: '147028699252',
    projectId: 'thriller-multiverse',
    storageBucket: 'thriller-multiverse.firebasestorage.app',
    iosBundleId: 'com.example.thrillerMultiverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLh4xpgMFfV5v1x6nlfaR0j66o7uu5yE',
    appId: '1:147028699252:ios:11a51af79fe2028d7c8921',
    messagingSenderId: '147028699252',
    projectId: 'thriller-multiverse',
    storageBucket: 'thriller-multiverse.firebasestorage.app',
    iosBundleId: 'com.example.thrillerMultiverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnWIdBQ4DbNQKtKwmaXYihs-dGvupLT10',
    appId: '1:147028699252:web:330310fb0c9146897c8921',
    messagingSenderId: '147028699252',
    projectId: 'thriller-multiverse',
    authDomain: 'thriller-multiverse.firebaseapp.com',
    storageBucket: 'thriller-multiverse.firebasestorage.app',
  );
}
